# Run firebird server for integration tests

services:
  db:
    image: jacobalberty/firebird:v5.0.0@sha256:a9d407892a9efa005f6456c0bb6daccabe73f747707663249ea6d061c5defe66
    ports:
      - 127.0.0.1:3050:3050/tcp
    environment:
      FIREBIRD_DATABASE: tests_database.fdb
      FIREBIRD_USER: tests_user
      FIREBIRD_PASSWORD: tests_password
