name: Deploy docs

on:
  push:
    branches: [main]
    paths:
      - docs/**/*.md
      - src/**/*.py
      - mkdocs.yml

permissions:
  contents: write

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup vapoursynth
        uses: deadnews/action-setup-vs@latest

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          cache: poetry

      - name: Install deps
        run: poetry install

      - name: Deploy docs
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          poetry run mkdocs gh-deploy --force
