name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: read

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          cache: poetry

      - name: Install deps
        run: poetry install

      - name: Lint code
        run: poetry run poe ci

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
        firebird-version: ["2.5-sc", "latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup firebird container
        uses: juarezr/firebirdsql-github-action@v1.2.0
        with:
          version: ${{ matrix.firebird-version }}
          firebird_database: my_database.fdb
          firebird_user: my_user
          firebird_password: my_password

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install deps
        run: poetry install

      - name: Run tests
        run: poetry run pytest --cov-report=xml

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.firebird-version == '2.5-sc' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v3

  publish-pypi:
    name: Release to PyPI
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [lint, tests]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning[plugin]

      - uses: actions/setup-python@v4

      - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.6
